name: report-test
on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Run Test Suite
      run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --output love12.zip --url "https://api.github.com/repos/love2d/love/actions/artifacts/971298535/zip"
        7z x love12.zip -o*
        ls
        love12/love.app/Contents/MacOS/love main.lua
    - name: Love Test Report
      uses: ellraiser/love-test-report@main
      with:
        name: Love Testsuite MacOS
        title: macos-test-report
        path: output/lovetest_runAllTests.md
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Install Mesa 
      run: |
        curl -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/23.2.1/mesa3d-23.2.1-release-msvc.7z
        7z x mesa.7z -o*
        powershell.exe mesa\systemwidedeploy.cmd 1
    - name: Run Test Suite
      run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --output love12.zip --url "https://api.github.com/repos/love2d/love/actions/artifacts/971298540/zip"
        7z x love12.zip -o*
        7z x love12/love-12.0-win64.zip -o*
        love12\love-12.0-win64\lovec.exe main.lua
    - name: Love Test Report
      uses: ellraiser/love-test-report@main
      with:
        name: Love Testsuite Windows
        title: windows-test-report
        path: output/lovetest_runAllTests.md
  linux-os:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Run Test Suite
      run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --output love12.AppImage --url "https://api.github.com/repos/love2d/love/actions/artifacts/971298534/zip"
        chmod a+x love12.AppImage
        ls
        xvfb-run --auto-servernum love12.AppImage main.lua
    - name: Love Test Report
      uses: ellraiser/love-test-report@main
      with:
        name: Love Testsuite Linux
        title: linux-test-report
        path: output/lovetest_runAllTests.md
