name: report-test
on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Love Test Report
      uses: ellraiser/love-test-report@main
      with:
        name: Love Testsuite MacOS
        title: macos-test-report
        path: examples/lovetest_runAllTests.md
  windows:
    runs-on: windows-latest
    steps:
    - name: Get sample file
      uses: actions/checkout@v4
    - name: Install Mesa 
      run: |
        curl -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/23.2.1/mesa3d-23.2.1-release-msvc.7z
        7z x mesa.7z
        powershell.exe ./systemwidedeploy.cmd 1
    - name: Download Love
      run: |
        curl -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L -o love12.zip "https://github.com/love2d/love/suites/17006638388/artifacts/971298540"
        tar -xf love12.zip
        tar -xf love12/love-12.0-win64.zip
    - name: Run Test Suite
      run: love12\love-12.0-win64\lovec.exe ./
    - name: Love Test Report
      uses: ellraiser/love-test-report@main
      with:
        name: Love Testsuite Windows
        title: windows-test-report
        path: examples/lovetest_runAllTests.md
  linux-os:
    runs-on: ubuntu-20.04
    steps:
    - name: Get sample file
      uses: actions/checkout@v4
      with:
        sparse-checkout: examples/lovetest_runAllTests.md
    - name: Love Test Report
      uses: ellraiser/love-test-report@main
      with:
        name: Love Testsuite Linux
        title: linux-test-report
        path: examples/lovetest_runAllTests.md
